server:
  port:8080
file:
  path: /home/pic/
  host: http://182.61.168.164:8080/pic/

spring:
  mvc:
    static-path-pattern: /pic/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  cache: false
  redis:
    database: 0
    host: 182.61.168.164
    port: 6379
    password: **
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 1
    timeout: 1000
